CREATE TABLE Users (
	UserID 			INT NOT NULL AUTO_INCREMENT,
	Username		VARCHAR(35) NOT NULL UNIQUE,
	FullName       VARCHAR(255) NOT NULL,
	Email 			VARCHAR(100) NOT NULL UNIQUE,
	Password	 	VARCHAR(20),
	PRIMARY KEY (UserID)
);

CREATE TABLE Album (
	UserID			INT NOT NULL,
	AlbumID			INT NOT NULL AUTO_INCREMENT,
	AlbumName		VARCHAR(255) NOT NULL,
	Description		VARCHAR(555),
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	PRIMARY KEY (AlbumID)
);

CREATE TABLE Photo (
	UserID			INT NOT NULL,
	AlbumID			INT NOT NULL,
	PhotoID			INT NOT NULL AUTO_INCREMENT,
	PhotoName		VARCHAR(255) NOT NULL,
	Description		VARCHAR(555),
	PhotoSize		INT	NOT NULL CHECK(PhotoSize < 4194304),
	PhotoDate		DATETIME,
	SourcePath		VARCHAR(555) NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	FOREIGN KEY (AlbumID) REFERENCES Album(AlbumID),
	PRIMARY KEY (PhotoID)
);